import {
  END,
  START,
  StateGraph,
  StateSchema,
  type GraphNode,
} from "@langchain/langgraph";
import z from "zod";
import { geminiModel, mistralAIModel, openAIModel } from "./model.ai.js";
import { createAgent, HumanMessage, toolStrategy } from "langchain";

const state = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
  }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
  const [mistralResponse, geminiResponse] = await Promise.all([
    mistralAIModel.invoke(state.problem),
    geminiModel.invoke(state.problem),
  ]);

  return {
    solution_1: String(mistralResponse.content || ""),
    solution_2: String(geminiResponse.content || ""),
  };
};

const judgeNode: GraphNode<typeof state> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  const judge = createAgent({
    model: openAIModel,
    responseFormat: toolStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
      }),
    ),

    systemPrompt: `You are judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 each solution, along with your reasoning for the scores.`,
  });

  const judgeResponse = await judge.invoke({
    messages: [
      new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evalute the solutions and provides and reasoning.
                `),
    ],
  });

  const data = judgeResponse.structuredResponse || judgeResponse;
  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
  } = data;

  return {
    judge: {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning,
    },
  };
};

const graph = new StateGraph(state)
  .addNode("solution", solutionNode)
  .addNode("judge_node", judgeNode)
  .addEdge(START, "solution")
  .addEdge("solution", "judge_node")
  .addEdge("judge_node", END)
  .compile();

export default async function (problem: string) {
  const result = await graph.invoke({
    problem: problem,
  });

  return result;
}
